pipeline {
    agent any
    environment {
        DOCKER_CONTEXT = 'default'
    }
    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/cristopher-torres/EvaluacionTingeso1']])
                dir("ToolRent_FRONTEND") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                dir("ToolRent_FRONTEND") {
                    script {
                        withDockerRegistry(credentialsId: 'docker-credentials') {
                            bat "docker build -t crisdocker10/toolrent-frontend:latest ."
                            bat "docker push crisdocker10/toolrent-frontend:latest"
                        }
                    }
                }
            }
        }
    }
}